// Nombres de juego en español para mostrar en la UI; la API identifica cada versión con un slug en inglés.
export const VERSION_NAMES_ES = {
  red: "Rojo",
  blue: "Azul",
  yellow: "Amarillo",
  gold: "Oro",
  silver: "Plata",
  crystal: "Cristal",
  ruby: "Rubí",
  sapphire: "Zafiro",
  emerald: "Esmeralda",
  firered: "Rojo Fuego",
  leafgreen: "Verde Hoja",
  diamond: "Diamante",
  pearl: "Perla",
  platinum: "Platino",
  heartgold: "Oro HeartGold",
  soulsilver: "Plata SoulSilver",
  black: "Negro",
  white: "Blanco",
  "black-2": "Negro 2",
  "white-2": "Blanco 2",
  x: "X",
  y: "Y",
  "omega-ruby": "Rubí Omega",
  "alpha-sapphire": "Zafiro Alfa",
  sun: "Sol",
  moon: "Luna",
  "ultra-sun": "Ultrasol",
  "ultra-moon": "Ultraluna",
  "lets-go-pikachu": "Let's Go, Pikachu!",
  "lets-go-eevee": "Let's Go, Eevee!",
  sword: "Espada",
  shield: "Escudo",
  "brilliant-diamond": "Diamante Brillante",
  "shining-pearl": "Perla Reluciente",
  "legends-arceus": "Leyendas Pokémon: Arceus",
  scarlet: "Escarlata",
  violet: "Púrpura",
};

const capitalizar = (texto) => texto.charAt(0).toUpperCase() + texto.slice(1);

export const translateVersion = (version) => VERSION_NAMES_ES[version] ?? capitalizar(version.replace(/-/g, " "));
